version: 2
jobs:
  macOS:
    macos:
      xcode: "11.4.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Install CMySQL and CTLS
          command: |
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew tap vapor/homebrew-tap
            brew install cmysql
            brew install ctls
            brew install libressl
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
      - run:
          name: Report coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: v1-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build
  Linux:
    docker:
      - image: vapor/swift:5.2-xenial
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Copy Package file
          command: cp Package.swift res
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test --enable-test-discovery --sanitize=thread
      - run:
          name: Restoring Package file
          command: mv res Package.swift
      - save_cache:
          key: v2-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build
workflows:
  version: 2
  build-and-test:
    jobs:
      - macOS
      - Linux
experimental:
  notify:
    branches:
      only:
        - master
        - develop
